; This file was automatically generated by ScriptHubImporter.py
global g_ImportsGameVersion64 := 632
<<<<<<< HEAD
global g_ImportsGameVersionPostFix64 := ".3"
=======
global g_ImportsGameVersionPostFix64 := ""
>>>>>>> 2c5be581a36002d1a8181937ba293b014543facc
global g_ImportsGameVersionPlatform64 := "Steam"